### ISSUE TITLE
Non US-ASCII Characters, File URIs in Windows

### ISSUE THREAD

**Issue by yhata** [mganss/HtmlSanitizer#106]
Can I get a non-US-ASCII character directly in a local file path ? (without percent-encoding)
https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/

**Non US-ASCII Characters**

> Incorrect: file:///C:/example%E3%84%93.txt
> Correct: file:///C:/exampleㄓ.txt

Example:
https://dotnetfiddle.net/QUCun3

**Comment by mganss** [comment]
This occurs because we're using [`Uri.AbsoluteUri`](https://msdn.microsoft.com/en-us/library/system.uri.absoluteuri) when sanitizing URIs.  You can work around it like so:
```C#
var sanitizer = new HtmlSanitizer();
sanitizer.RemovingAttribute += (s, e) =>
    e.Cancel = e.Reason == RemoveReason.NotAllowedUrlValue
    && e.Attribute.Value.StartsWith("file:///", StringComparison.OrdinalIgnoreCase);

var html = @"<a href=""file:///C:/exampleㄓ.txt"">test</a>";

var actual = sanitizer.Sanitize(html);

Assert.Equal(html, actual);
```

Use of the `Uri` class also results in #66, btw. My plan is to replace it with something else in a future version.

N.B. Github's sanitizer has the same bug/feature: http://www.example.com/exampleㄓ.txt

**Comment by yhata** [comment]
Hi @mganss .
It's is a pretty nice workaround.

Thank you very much!
https://dotnetfiddle.net/7x0499
