### ISSUE TITLE
Allow `data:image/*` but not `data:text/javascript`

### ISSUE THREAD

**Issue by jaywick** [mganss/HtmlSanitizer#122]
I'm trying to see if it is possible to allow through

```html
<img src="data:image/gif;base64,iMjUStAnINNocEnTStrNGsiR">
```

But not

```html
<img src="data:text/javascript;base64,aLlyOurBaSE64arEbElONgtOUS">
```

Either via white/black listing. Is that possible here? I can only allow _all_ data schemes which is unideal with

```csharp
santiser.AllowedSchemes.Add("data");
```

**Comment by mganss** [comment]
If you want more control over which URLs you want to allow you can user the `RemovingAttribute` event. In that case, you need to *not* add the data scheme to the `AllowedSchemes` otherwise the event won't be triggered for data URLs.

IMO it is overkill to try and filter specific MIME types, though. Keep in mind that the same would have to apply to HTTP URLs as well, only in that case you have no control over which MIME type the server responds with.

**Comment by jaywick** [comment]
Excellent, didn't see the `RemovingAttribute` which is pretty good, I do agree the MIME isn't perfect to check against.
