### ISSUE TITLE
CSS (shorthand) properties getting removed

### ISSUE THREAD

**Issue by Epicycle23** [mganss/HtmlSanitizer#178]
Hello,

just stumbled over this, not sure if it's a known issue/wanted behaviour but when sanitizing the following fragment with default settings the style tag gets removed completely:

`new HtmlSanitizer().Sanitize("<p><span style=\"text-decoration: underline;\">bla</span></p>");`

When iterating the styles it checks for text-decoration-style, text-decoration-color and text-decoration-line instead of text-decoration (the actual CssText) which is included in AllowedCssProperties while the former ones are not.

Found on current master and 5.0.218-beta package.
My apologies if this is intended I just find it odd because the text-decoration property is included in the default allowed css properties.

**Comment by mganss** [comment]
AngleSharp.Css expands shorthand properties into longhands since 0.10 (see https://github.com/AngleSharp/AngleSharp.Css/issues/9). 

I guess we'll have to add all the longhand property names to the default list of allowed properties.

**Comment by mganss** [comment]
I've added the longhands for which we had shorthands already in the configuration and will update docs accordingly.

**Comment by om-ha** [comment]
Happy holidays @mganss 

Could you please push the latest version (v5.0.287) to NuGet?
[Release Tag](https://github.com/mganss/HtmlSanitizer/releases/tag/v5.0.287)
[Commit](https://github.com/mganss/HtmlSanitizer/commit/e114c6f4e1f8ebd0c11e6f88430e7c96355323f1)


It has this issue's fix that I want.

A bunch of my style tags are gone when sanitizing 😶rendering the output HTML undesirable. 
I want to try this solution addressed in this issue. But I can't because it's not on NuGet.

If you can't push to NuGet, do you recommend any other alternatives? Should I build HtmlSanitizer myself and including it as a DLL?

**Comment by mganss** [comment]
Happy holidays @om-ha  This is included in [5.0.274-beta](https://www.nuget.org/packages/HtmlSanitizer/5.0.274-beta).

**Comment by om-ha** [comment]
@mganss Thanks! I see.. then my problem still persists even with this fix.

My issue has a different root cause. Created a new one [here](https://github.com/mganss/HtmlSanitizer/issues/203).

And issue was solved of course!! thanks for the great library.
