### ISSUE TITLE
use the methods "UriAttributes.Remove" and "AllowedSchemes.Add", some unexpected result appear

### ISSUE THREAD

**Issue by LeonaYen** [mganss/HtmlSanitizer#228]
Hi
When I try to use the methods "UriAttributes.Remove" and "AllowedSchemes.Add", some unexpected result appear, as the URL "https://dotnetfiddle.net/eNJfEx".

1. (test case 6) Line 19：When I try to remove the "src" from the allowed UriAttribute by "UriAttributes.Remove("src");", the "<img src=...>" character still exists in the sanitized-result string.
2. test case 7 Line 28：When I try to add the "mailto" from the allowed scheme by "AllowedSchemes.Add(mailto);", there is NO "<img src="mailto:\\...">" string in the sanitized-result string.

Can you help know what happened in my code?

**Comment by mganss** [comment]
I'm not sure I understand what you are trying to achieve.

1. The `UriAttributes` collection contains the attributes that may contain URIs (e.g. href and src). It does not contain attributes that are whitelisted. This is what the `AllowedAttributes` collection is for. So if you want the src attribute to be removed, remove `"src"` from the `AllowedAttributes` collection.

2. If you add "mailto" to the collection of whitelisted protocol schemes, URIs that have this protocol scheme will not be removed. But in your example there is no URI with a mailto protocol in the input. What's confusing to me is that you specify a (non well-formed) mailto URI as the second argument to `Sanitize`. This argument is supposed to specify a base URI for relative URIs, e.g. if you specified `https://www.example.com/` as the base URI, a relative URI such as in `src="test.gif"` would result in `src="https://www.example.com/test.gif"`. A well-formed mailto URI would be `mailto:test@example.com`. Since you removed src from the collection of URI attributes, it stays "test.gif", otherwise it would be replaced by "mailto://test.gif".
