### ISSUE TITLE
Html sanitize css property background-repeat

### ISSUE THREAD

**Issue by lukapor** [mganss/HtmlSanitizer#243]
Attached file sample  htmlBackgroundNoRepeat.html has css property background-repeat. When I sanitize html, property is gone and sanitize html is broken (cleanHtmlBackgroundNoRepeat.html).
[attachedFiles.zip](https://github.com/mganss/HtmlSanitizer/files/5407431/attachedFiles.zip)

**Comment by mganss** [comment]
Here's the original HTML (please post such short snippets directly in the issue comments):

```html
<div style="font-size: 12pt; font-family: 'Segoe UI';">
    <div fr-original-style="width: 400px; height: 400px; background-image: url('https://user-images.githubusercontent.com/42636057/96471112-437d9a80-122f-11eb-86c2-f30d9b0c8054.png'); background-repeat: no-repeat;"
        style="width: 400px; height: 400px; background-image: url('https://user-images.githubusercontent.com/42636057/96471112-437d9a80-122f-11eb-86c2-f30d9b0c8054.png'); background-repeat: no-repeat;">
        test</div>
</div>
```

This is a bug that occurs because the parser unravels shorthand CSS properties such as `background-repeat` to their longhand representations such as `background-repeat-x` and `background-repeat-y`. I'll add the missing longhand values to the default configuration. In the meantime, you can add the missing values yourself by doing

```c#
sanitizer.AllowedCssProperties.Add("background-repeat-x");
sanitizer.AllowedCssProperties.Add("background-repeat-y");
```

Do you mean this by broken or do you think there is an additional issue? It seems that in the attached output file the newlines are missing but I can't repro that.

**Comment by mganss** [comment]
While the above is true as a cause for the issue it seems there aren't officially CSS properties `background-repeat-x` and `background-repeat-y`. Investigating.

**Comment by mganss** [comment]
Chromium implements this partially (you can still see it in dev tools) and there were discussions to add it to the specification but it was decided against AFAICT: https://github.com/w3c/csswg-drafts/issues/116
I'll add the longhands nonetheless to solve this issue.
