### ISSUE TITLE
CkEditor5

### ISSUE THREAD

**Issue by andrewgeorgesands** [mganss/HtmlSanitizer#249]
Hi and thanks for the framework.  We use it with great success. However (isn't it always), when migrating to CkEditor5, we noticed that the htmlsanitizer breaks the CkEditor's custom model when using fonts that contain spaces in the name (for example comic sans and times new roman).  I've narrowed it down to the use of AngleSharp ToCss() when parsing inline styles.  

Would it be possible to configure the htmlsanitizer to not use the AngleSharp css parser when sanitizing inline styles?

This is the input from CkEditor5 on the wire as it is received by our backend
`<p><span style=\"font-family:'Comic Sans MS', cursive;font-size:12pt;\">comic</span>`

This is what we return on the wire as output after it has been run through the sanitizer
`<p><span style=\"font-family: &quot;Comic Sans MS&quot;, cursive; font-size: 12pt\">comic</span>`

Where the single quotes have been changed to double quotes then html encoded, it unfortunately breaks CkEditor5 which defaults back to whatever the default font is (and I really want to support comic sans and times new roman)

**Comment by mganss** [comment]
The `&quot;`s are introduced by the `Attribute` method of the `IMarkupFormatter` for which you can provide your own implementation using the `OutputFormatter` and `DefaultOutputFormatter` properties.

Assuming I understand your use case correctly I would suggest a different approach though: Use the unsanitized (but escaped) input as input to the editor so that the user sees exactly what they had entered previously and only use the sanitized output for display on your web page.

**Comment by andrewgeorgesands** [comment]
Thank your for your quick response!  I will use your suggestion to not sanitize input from ckeditor5 as long as we can control that the unsanitized payload is not used anywhere else.  Unfortunately we use the same storage for ckeditor4 and that version is riddled with XSS vulns so it must be sanitized before returning to the editor (but that is my problem, not yours)
