### ISSUE TITLE
How to allow css like ::-webkit-scrollbar ?

### ISSUE THREAD

**Issue by sikkamukul** [mganss/HtmlSanitizer#322]
Attaching the sample code :-
  ::-webkit-scrollbar-thumb {
	  background: #888
  }
  Is being removed on sanitization from style tag
  Kindly help to retain it after sanitization

**Comment by mganss** [comment]
Unfortunately, this currently doesn't work due to an issue within AngleSharp.Css. See https://github.com/AngleSharp/AngleSharp.Css/issues/98

Perhaps you can work around the issue by modifying your use case. Do you really want to allow users to input whole style sheets containing vendor specific selectors?

**Comment by sikkamukul** [comment]
Yes, this use case allows users to enter psuedo elements in css style. Any workaround you would suggest for the same?

**Comment by mganss** [comment]
No, can't think of a workaround 🤷🏻 Hopefully, this gets addressed by AngleSharp.Css soon.

**Comment by pragatibaheti** [comment]
Related doubt. Also, does it consider nested CSS classes (scss) in style tags while sanitization? 
``` 
.some-class {
  &.another-class {}
}
```

**Comment by mganss** [comment]
@pragatibaheti No, this isn't even supported by any browser: https://caniuse.com/css-nesting

**Comment by mganss** [comment]
Fixed in 7.0.473 (through AngleSharp 0.16.3)
