### ISSUE TITLE
strange insertation of p tags

### ISSUE THREAD

**Issue by utillity** [mganss/HtmlSanitizer#338]
Hi,

thanks for this great package!

my input string

````
<p><figure style="width: 100%" class="image"><img data-cid="aaa" data-att-id="bbb" /></figure></p>
<p><figure class="media"><oembed src="https://player.vimeo.com/video/..."></oembed></figure></p>
````

becomes
````
<p></p>
<figure style="width: 100%" class="image"><img data-cid="aaa" data-att-id="bbb"></figure>
<p></p>
<p></p>
<figure class="media"><oembed src="https://player.vimeo.com/video/..."></oembed></figure>
<p></p>
````

any idea why?

**Comment by mganss** [comment]
I think this might be because [`figure`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure) which is a [flow content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#flow_content) element is not valid as child element of [`p`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p) which accepts only [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content) elements as child elements.

When it encounters the opening `figure` tag it assumes a closing tag for `p` was omitted and when it encounters the closing `p` tag after `</figure>` it assumes the corresponding opening tag for `p` was omitted.

**Comment by utillity** [comment]
ah, great input! Really appreciate it! Thanks!
