### ISSUE TITLE
Consider AngleSharp to replace CsQuery

### ISSUE THREAD

**Issue by 304NotModified** [mganss/HtmlSanitizer#34]
From the OWASP top-10 (2013)
> A9 Using Components with Known Vulnerabilities

* Libraries which has a lot of issues and aren't actively maintained, are as risk.
* The CsQuery library is not actively maintained and has a growing amount of issues.  

Consider replacing CsQuery with [AngleSharp](https://github.com/FlorianRappl/AngleSharp) in the (near) future - [as suggested by the creator and only owner of CsQuery](https://github.com/jamietre/CsQuery/issues/173#issuecomment-101727143).

**Comment by mganss** [comment]
I started a port to AngleSharp (AngleSharp branch). A large number of tests are not passing yet, though. This is mostly due to FlorianRappl/AngleSharp#101.

**Comment by 304NotModified** [comment]
:+1:

**Comment by 304NotModified** [comment]
I see some discussion at the Github issue of AngleAsharp. Do you think they will solve the things that are needed for the replacement?

**Comment by mganss** [comment]
I've just pushed an update to the AngleSharp branch with only around 10 tests still failing. I think most if not all of these only have to be changed so that the expected output matches the actual output.

**Comment by thefringeninja** [comment]
I see that there is a nuget package for this https://www.nuget.org/packages/HtmlSanitizer/3.1.67-beta and that all tests of the AngleSharp branch pass on my machine. Can this be merged back into master yet?

**Comment by mganss** [comment]
I'm planning to do this in a couple of days if no issues pop up during that time. Does the beta work for your use case?

**Comment by thefringeninja** [comment]
Yes it does, and I don't mind depending on a pre release package for the
time being. Take your time :) I'll report any issues here if I get them.

On Thu, Nov 26, 2015 at 3:22 PM, Michael Ganss <notifications@github.com>
wrote:

> I'm planning to do this in a couple of days if no issues pop up during
> that time. Does the beta work for your use case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mganss/HtmlSanitizer/issues/34#issuecomment-159926466>
> .
>



-- 
Sent from my regular computer
http://twitter.com/thefringeninja
http://www.thefringeninja.com/

**Comment by rmichela** [comment]
Any plans on merging the anglesharp branch to master?

**Comment by mganss** [comment]
Yes, any day now. I want to include #51 and then merge to master.

**Comment by StanislavPrusac** [comment]
(y) for AngleSharp

**Comment by mganss** [comment]
3.1.76 uses AngleSharp instead of CsQuery.

**Comment by tiesont** [comment]
@mganss I realize the train has left the station already on this, but given that AngleSharp seems to be the root cause of a disproportionate number of new issues, are you really gaining anything over using CsQuery? I personally found CsQuery easier to use; does AngleSharp provide functionality not present in CsQuery, or is it just that AngleSharp is actively maintained?

**Comment by mganss** [comment]
It's mostly because AngleSharp is actively maintained. Just yesterday I opened two PRs and got a response within minutes. In contrast, look what happened with #36.

I also found CsQuery easier to use. I don't think that for our use case there is functionality in AngleSharp that's missing from CsQuery. But there's one aspect I have come to appreciate in AngleSharp: It does exactly the same as a browser, even the API is mostly identical, i.e. you can take any HTML snippet and try it in the browser console.

**Comment by tiesont** [comment]
Fair enough. Hopefully, once AngleSharp gets to the 1.0 milestone, they'll realize they can't keep introducing breaking changes. Thanks for the response.

**Comment by 304NotModified** [comment]
> . Hopefully, once AngleSharp gets to the 1.0 milestone, they'll realize they can't keep introducing breaking changes.

Couldn't agree more! 

PS: CSQuery is also not ported to netstandard, and that is of course important for the (near) future.

**Comment by 304NotModified** [comment]
Looks like 1.0 is near for AngleSharp:

![image](https://cloud.githubusercontent.com/assets/5808377/21199301/3d242450-c243-11e6-9cd5-7db3a9322206.png)
