### ISSUE TITLE
Throws exception on multiple recipients in a email.

### ISSUE THREAD

**Issue by shivinsky** [mganss/HtmlSanitizer#41]
Sanitize the following HTML with enabled `mailto:` scheme:
```html
<a href="mailto:bonnie@example.com,clyde@example.com">Bang Bang</a>
```
**Actual:**
```
System.UriFormatException : Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateHostStringHelper(String str, UInt16 idx, UInt16 end, ref Flags flags, ref String scopeId)
   at System.Uri.CreateHostString()
   at System.Uri.GetComponentsHelper(UriComponents uriComponents, UriFormat uriFormat)
   at System.Uri.GetComponents(UriComponents components, UriFormat format)
   at System.Uri.get_AbsoluteUri()
   at Ganss.XSS.HtmlSanitizer.SanitizeUrl(String url, String baseUrl)
   at Ganss.XSS.HtmlSanitizer.Sanitize(String html, String baseUrl, IOutputFormatter outputFormatter)
```
**Expected:**
No exception is thrown.

**Comment by Jawvig** [comment]
This is unlikely to change the result, but I did note in RFC 2368 that the comma should apparently be encoded. See http://www.ietf.org/rfc/rfc2368.txt and in particular the example at the end of page 1.

**Comment by 304NotModified** [comment]
I think HtmlSanitizer should "eat"  the exception?

**Comment by shivinsky** [comment]
@Jawvig seems like `System.Uri` is not very consistent. For example, I could not reproduce the same behaviour for `http:` scheme.
So, I agree with @304NotModified. Probably, ignoring exception and stripping "invalid" `href` is way to go.

**Comment by 304NotModified** [comment]
Some info about the (annoying) system uri.  See #8
http://blogs.msdn.com/b/ncl/archive/2010/02/23/system-uri-f-a-q.aspx

**Comment by 304NotModified** [comment]
Ps @mganss great covery results!

**Comment by mganss** [comment]
@Jawvig RFC 2368 was superseded by [RFC 6068](https://tools.ietf.org/html/rfc6068) which allows unencoded commas:
```
mailtoURI    = "mailto:" [ to ] [ hfields ]
to           = addr-spec *("," addr-spec )
...
```
In .NET 4.5 and above no exception is thrown because `Uri.TryCreate()` returns false and the URI is stripped. But of course this means that `System.Uri` is currently not compliant with RFC 6068 and Microsoft doesn't seem to have the intention to fix it soon: https://connect.microsoft.com/VisualStudio/feedback/details/794758/system-uri-incorrectly-rejects-mailto-uris

I agree that the best way to deal with this issue is to catch the exception and strip the URI although it's legal. If someone insisted on keeping these kinds of URIs, they'd have to handle `RemovingAttribute` and check the URI themselves.

@304NotModified Thanks :smile:
