### ISSUE TITLE
Doesn't test for all character escape sequences

### ISSUE THREAD

**Issue by mycall** [mganss/HtmlSanitizer#49]
Looking @ https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet#Character_escape_sequences

I don't see where all of these combinations are tested.   Is this a new test?  If so, are there other tests that need to be added/reexamined?

**Comment by 304NotModified** [comment]
I looks new to me. Also:

>
Last revision (mm/dd/yy): 10/12/2015

Good idea to check the list!

**Comment by mganss** [comment]
This section has been there since at least [2012 according to archive.org](https://web.archive.org/web/20121015153755/https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet#Character_Encoding), i.e. since before this library was written. It doesn't describe a specific exploit that can be tested against. Do you have a specific exploit in mind that isn't currently taken care of?

**Comment by mganss** [comment]
Closing this because no feedback.
