### ISSUE TITLE
Sanitize not removing span tags

### ISSUE THREAD

**Issue by goatrodeosoftware** [mganss/HtmlSanitizer#563]
I've got HTML with a span tag and the sanitizer isn't removing it despite it not being in the allowed tags list:

```
using Ganss.Xss;

string html = "<span>Payment via check, Zelle, money order, wire transfer. Shipping is $25 in continental US, international is at cost using FedEx. Insurance is extra and on buyer to pay. Time payments available. Contact to discuss terms.</span>";
HtmlSanitizer sanitizer = new HtmlSanitizer()
{
    AllowedTags = { "br", "a", "b" }
};
string result = sanitizer.Sanitize(html);
Console.WriteLine(result);
```

**Comment by mganss** [comment]
This is due to the way collection initializers work in C#. The `HtmlSanitizer` constructor initializes the `AllowedTags` set to a non-empty set that contains `span` and the collection initializer then calls the `Add` method. You'll need to clear the `AllowedTags` set, then add the tags you want to allow or use the `HtmlSanitizerOptions` class:

```c#
var options = new HtmlSanitizerOptions()
{
    AllowedTags = { "br", "a", "b" }
};
var sanitizer = new HtmlSanitizer(options);
```
