### ISSUE TITLE
CDATA should not be sanitized

### ISSUE THREAD

**Issue by nZeus** [mganss/HtmlSanitizer#85]
Hi,

I've tried the following string: `<![CDATA[<p>Value</p>]]>`. After the sanitization I have `Value<p></p>]]&gt;` that is incorrect. 
As I understand, it should not be changed at all.

Right now there is no way to allow CDATA.
Could you please add support for CDATA?

Best regards,
Ilia

**Comment by mganss** [comment]
CDATA is not for use in HTML, [the spec](https://www.w3.org/TR/html5/syntax.html#cdata-sections) says:

> CDATA sections can only be used in foreign content (MathML or SVG).

Browsers behave the same way:

```javascript
document.body.innerHTML = '<![CDATA[<p>Value</p>]]>';
document.body.innerHTML 
→ "<!--[CDATA[<p-->Value<p></p>]]&gt;"
```

The comment is stripped by HtmlSanitizer.

I think it would be dangerous if HtmlSanitizer let CDATA sections pass through because these could contain XSS attack vectors which would be interpreted as HTML by conformant parsers (as the example shows).

**Comment by nZeus** [comment]
Hi!

Yep, you convinced me!
I'm closing the issue.

Thanks for your time!
