### ISSUE TITLE
Allow Non HTML tags

### ISSUE THREAD

**Issue by MohanVijayakumar** [mganss/HtmlSanitizer#91]
Hi,

I have the string like below in my input
`The diameter starts <MM 78 > radial`
In the above string i get only `The diameter starts`. Is there anyway to get the string as full as it does not contain any HTML tags

Thanks

**Comment by mganss** [comment]
The HTML parser parses the input as `The diameter starts <mm 78=""> radial</mm>`, then strips the `mm` element. If there was a space before the mm, i.e. `< mm`, you'd get `The diameter starts &lt; MM 78 &gt; radial`.

I currently see no elegant way out of this dilemma. You could pre-process your input by inserting a zero width space (`&#8203;`) after every < which is not followed by one of your allowed element tag names or slash.

**Comment by mganss** [comment]
I came across this problem myself recently so I hacked up a [gist](https://gist.github.com/mganss/00bec2c2245c0ef86d9c82d6211def7b).

A few things to note:
- The HTML elements recognized are a combination of [HTML 4](https://www.w3.org/TR/1999/REC-html401-19991224/index/elements.html) and [HTML 5](http://w3c.github.io/html-reference/elements.html).
- Tags are matched with a regex which may fail if you've got `<` within attributes (although I'm not sure this is really a problem in this particular case since we're only replacing `<` with `&lt;`).
- When a "non-HTML" element is encountered, the `<` is replaced by `&lt;` which causes the sanitizer to not recognize it as an HTML element. I think that's less hacky than the approach I suggested above.
- Obviously this will not take care of cases where the input contains actual HTML elements which are not intended to be recognized as such.
