### ISSUE TITLE
<br /> gets sanitized to <br>.....

### ISSUE THREAD

**Issue by tonywiredin** [mganss/HtmlSanitizer#97]
..... which is less than ideal.

to reproduce:

		var sanitizer = new HtmlSanitizer();
		var html = @"<br />";
		var sanitized = sanitizer.Sanitize(html);
		Console.WriteLine(sanitized);

**Comment by mganss** [comment]
This occurs because the input is parsed, then rendered back out. The default formatter renders HTML where self-closing tags are not used (though accepted for some elements like br). 

If you want XHTML output, you can use the `XhtmlMarkupFormatter`. If you want HTML but self-closing tags for void elements like br, you can roll your own formatter (perhaps by deriving from or copying `HtmlFormatter`).

In either case, you'd set either the `OutputFormatter` or `DefaultOutputFormatter` properties to an instance of your preferred formatter class.

**Comment by tonywiredin** [comment]
Thanks for the considered reply
